#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: lidar/pose
        # pose2d: lidar/ground_pose
        tf: tf
        child_frame_id: mocap/lidar
        parent_frame_id: world
markers:
    topic: markers
    parent_frame_id: world
optitrack_config:
        multicast_address: 224.0.0.1
        command_port: 1510
        data_port: 1511
        enable_optitrack: true
